aliases:
  - pw
  - pwarp
  - playerw
debug: false
autoUpdateMessages: true
restricted:
  - create
  - remove
  - list
  - listown
  - reload
  - updatemsg
cmdcolor: 6
cmdargs:
  create: create
  remove: remove
  list: list
  listown: listown
  reload: reload
  updatemsg: updatemsg
  warp: '<warp>'