aliases:
  - pw
  - pwarp
  - playerw
debug: false
autoUpdateMessages: true
worldsAsBlacklist: false
worlds:
  - world_the_end
  - world_nether
worldAlias:
  world: World
  world_the_end: The End
  world_nether: Nether
restricted:
  - create
  - remove
  - list
  - listown
  - reload
  - updatemsg
  - info
cmdcolor: 6
cmdargs:
  create: create
  remove: remove
  list: list
  listown: listown
  reload: reload
  updatemsg: updatemsg
  info: info
  warp: '<warp>'
