aliases:
  - pw
  - pwarp
  - playerw
debug: false
autoUpdateMessages: true
worldsAsBlacklist: true
worlds:
  - world_the_end
  - world_nether
worldAlias:
  world: World
  world_the_end: The End
  world_nether: Nether
warpDelay: 0
warpNameIgnoreCase: false
restricted:
  - create
  - remove
  - list
  - listown
  - reload
  - updatemsg
  - info
  - count
cmdcolor: 6
cmdargs:
  create: create
  remove: remove
  list: list
  listown: listown
  reload: reload
  updatemsg: updatemsg
  info: info
  count: count
  count-add: add
  count-del: del
  count-info: info
  player: '<player>'
  amount: '[amount]'
  warp: '<warp>'
