name: PlayerWarp
main: tk.Pdani.PlayerWarp.Main
version: 0.7.0
author: Pdani001
description: Adds the ability for players to create their own warps
website: https://pdani.tk/
softdepend: [Vault,Essentials]
permissions:
  playerwarp.use:
    description: Permission to use player warps
    default: true
  playerwarp.info:
    description: Permission to view information about a specified warp
    default: false
  playerwarp.create:
    description: Gives permission to create player warps
    default: false
  playerwarp.create.override:
    description: Permission to override existing warps
    default: false
  playerwarp.create.unsafe:
    description: Permission to create unsafe warps
    default: false
  playerwarp.remove:
    description: Gives permission to remove player warps
    default: false
  playerwarp.remove.others:
    description: Permission to remove other players warps
    default: false
  playerwarp.limit.unlimited:
    description: Permission to create unlimited warps
    default: false
  playerwarp.reload:
    description: Permission to reload warps and config
    default: false
  playerwarp.grant:
    description: Add or Del amount of warps allowed for a player
    default: false
  playerwarp.*:
    description: Give players with op everything by default
    default: op
    children:
      playerwarp.info: true
      playerwarp.grant: true
      playerwarp.create: true
      playerwarp.create.override: true
      playerwarp.create.unsafe: true
      playerwarp.remove: true
      playerwarp.remove.others: true
      playerwarp.limit.unlimited: true
      playerwarp.reload: true